name: Test and coverage
on:
  - push
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # setup golang
      - name: Install golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      # checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3
      # run tests
      - name: Run tests
        run: go test ./...
      # build coverage
      - name: Build coverage
        run: ./go_tests.sh && bash <(curl -s https://codecov.io/bash)
